# Generated by Django 4.1.10 on 2023-08-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodname', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('available', models.CharField(max_length=100)),
            ],
        ),
    ]
